import {el,sourceLink,toast} from './dom.js';
import {LearningStore} from './store.js';
import {roadmap,lessonView,reviewView} from './course.js';
import {translatorView} from './translator.js';
import {tutorView} from './tutor.js';
const main=document.getElementById('main');let course,store,destroy=()=>{},currentRoute='';
function refresh(){document.getElementById('savedCount').textContent=Object.keys(store.data.words).length;document.getElementById('lessonNav').href=`#lesson/${store.next().number}`;document.getElementById('saveProgress').checked=store.enabled;store.notice();}
function sources(){return el('article',{class:'panel sources'},el('p',{class:'eyebrow'},'Nguồn & quyền riêng tư'),el('h1',{},'Bạn học gì, dữ liệu ở đâu?'),el('h2',{},'Nội dung khóa học'),el('p',{},'Video là khóa Let’s Learn English — Level 1 của VOA Learning English, giữ nguyên trình phát và nguồn tác giả. Hướng dẫn tiếng Việt, ví dụ và câu hỏi tự luyện được Neural-Lingua biên soạn. Đây là sản phẩm học độc lập, không phải khóa chính thức của British Council.'),el('ul',{},...course.references.map(r=>el('li',{},sourceLink(r.url,r.name+' ↗')))),el('p',{},'VOA cho phép dùng nội dung do họ tự sản xuất khi ghi nguồn. Tài liệu của bên thứ ba phải có quyền riêng; web chỉ dùng các video chính thức đã có trong khóa này.'),el('h2',{},'Tiến độ và từ đã lưu'),el('p',{},'Tiến độ, điểm tốt nhất và sổ từ được lưu trong trình duyệt trên thiết bị này khi bật “Lưu tiến độ”. Không có tài khoản hoặc đồng bộ giữa các thiết bị. Tắt lưu sẽ xóa bản lưu trên thiết bị, nhưng bạn vẫn có thể học trong phiên đang mở. Dùng “Xóa dữ liệu học” để đặt lại.'),el('h2',{},'Video và dịch vụ bên ngoài'),el('p',{},'Video chỉ tải khi bạn bấm mở. Trình phát có thể kết nối hệ thống VOA và các nhà cung cấp của họ; khi chuyển bài hoặc đóng video, trình phát được gỡ khỏi trang. Lỗi hoặc giới hạn của nguồn có thể ảnh hưởng việc xem.'),el('p',{},'Văn bản dịch được gửi qua HTTPS tới dịch vụ Google khi bạn bấm Dịch. Lịch sử dịch mặc định tắt, tối đa 20 mục khi bật và có thể xóa riêng. Công cụ này chưa dùng API dịch có cam kết dịch vụ.'),el('p',{},'Ghi âm ở công cụ Dịch dùng model Whisper chạy ngay trong trình duyệt; âm thanh không gửi ra ngoài và không lưu. Micro chỉ bật sau thao tác Ghi âm. Model có thể lưu trong bộ nhớ trình duyệt và xóa riêng tại công cụ Dịch. Bản nháp luyện viết không tự gửi đi. Khi dùng gia sư local, câu hỏi và bản ghi chỉ gửi khi bạn thao tác; hội thoại không lưu và audio xử lý tạm thời. Giọng đọc tùy trình duyệt có thể sử dụng dịch vụ của nhà cung cấp.'),el('h2',{},'Mục tiêu học'),el('p',{},'Lộ trình hướng tới A1–A2. Một số bài cuối giới thiệu mẫu câu khó hơn; bạn có thể xem lại nhiều lần. Điểm bài tập và hoàn thành 52 bài phản ánh hoạt động tự luyện, không xác nhận trình độ CEFR. Thời lượng 25 phút mỗi bài chỉ là gợi ý.'),el('a',{href:'#roadmap'},'← Về lộ trình'));
}
function route(){if(!course)return;const parts=location.hash.slice(1).split('/'),kind=parts[0]||'roadmap';const key=kind==='lesson'?`lesson/${parts[1]}`:kind;document.title=(kind==='lesson'&&course.lessons[Number(parts[1])-1]?`Bài ${parts[1]}: ${course.lessons[Number(parts[1])-1].title}`:({roadmap:'Lộ trình tiếng Anh',review:'Ôn từ vựng',translate:'Dịch văn bản',sources:'Nguồn & quyền riêng tư'}[kind]||'Lộ trình tiếng Anh'))+' · Neural-Lingua';if(key!==currentRoute){destroy();destroy=()=>{};let node;if(kind==='lesson'){const n=Number(parts[1]);node=Number.isInteger(n)&&n>=1&&n<=52?lessonView(course,store,n,refresh):el('div',{class:'empty'},el('h1',{},'Bài học này chưa có'),el('a',{href:'#roadmap'},'Về lộ trình'));if(Number.isInteger(n)&&n>=1&&n<=52){const tutor=tutorView(course.lessons[n-1],{getDraft:()=>node.querySelector('#practiceDraft').value});node.querySelector('#practice').after(tutor.node);node.querySelector('.jump-links').append(el('a',{href:`#lesson/${n}/tutor`},'Gia sư AI'));destroy=tutor.destroy;}}else if(kind==='review')node=reviewView(course,store,refresh);else if(kind==='translate'){const view=translatorView();node=view.node;destroy=view.destroy;}else if(kind==='sources')node=sources();else node=roadmap(course,store,refresh);main.replaceChildren(node);currentRoute=key;main.setAttribute('aria-busy','false');main.focus({preventScroll:true});window.scrollTo(0,0);}for(const nav of document.querySelectorAll('[data-nav]')){if(nav.dataset.nav===kind||(kind==='roadmap'&&nav.dataset.nav==='roadmap'))nav.setAttribute('aria-current','page');else nav.removeAttribute('aria-current');}refresh();if(parts[2]&&['video','vocabulary','practice','quiz','tutor'].includes(parts[2])){const section=document.getElementById(parts[2]);section?.scrollIntoView();section?.setAttribute('tabindex','-1');section?.focus({preventScroll:true});}}
async function start(){try{const r=await fetch('data/course.json',{credentials:'omit'});if(!r.ok)throw new Error('Course unavailable');course=await r.json();if(!Array.isArray(course.lessons)||course.lessons.length!==52||new Set(course.lessons.map(l=>l.id)).size!==52||!course.lessons.every((l,i)=>l.number===i+1&&l.vocabulary?.length>=6&&l.quiz?.length===5&&l.media?.length))throw new Error('Invalid course');store=new LearningStore(course);route();}catch{main.setAttribute('aria-busy','false');main.replaceChildren(el('div',{class:'empty',role:'alert'},el('h1',{},'Chưa mở được khóa học'),el('p',{},'Kiểm tra kết nối và chạy trang bằng địa chỉ HTTP cục bộ theo README, rồi thử lại.'),el('button',{onclick:()=>location.reload()},'Tải lại')));}}
window.addEventListener('hashchange',route);
window.addEventListener('pagehide',()=>destroy());
document.getElementById('saveProgress').addEventListener('change',async e=>{if(!store)return;e.target.disabled=true;const ok=await store.setEnabled(e.target.checked);e.target.disabled=false;refresh();if(ok)toast(store.enabled?'Đã bật lưu tiến độ trên thiết bị.':'Đã tắt lưu; tiếp tục học trong phiên này.');});
const dialog=document.getElementById('resetDialog');document.getElementById('resetProgress').addEventListener('click',()=>dialog.showModal());document.getElementById('cancelReset').addEventListener('click',()=>dialog.close());document.getElementById('confirmReset').addEventListener('click',async()=>{if(!store)return;const ok=await store.reset();dialog.close();currentRoute='';if(location.hash==='#roadmap')route();else location.hash='roadmap';if(ok)toast('Đã xóa tiến độ, điểm và từ đã lưu.');});
window.addEventListener('learningchange',e=>{
 if(!store)return;refresh();
 if(e.detail?.external){
  if(e.detail.reset){currentRoute='';if(location.hash==='#roadmap')route();else location.hash='roadmap';return;}
  if(['roadmap','review'].includes(currentRoute)){currentRoute='';route();return;}
  const id=course.lessons[Number(currentRoute.split('/')[1])-1]?.id,p=store.data.lessons[id];
  const score=document.getElementById('savedLessonScore');if(score)score.textContent=`Điểm tốt nhất: ${p?.best||0}/5 · ${p?.complete?'Đã hoàn thành':'Đang học'}`;
  const complete=document.getElementById('completeLesson');if(complete){complete.disabled=p?.complete===true||(p?.best||0)<4;complete.textContent=p?.complete?'Đã hoàn thành ✓':'Đánh dấu hoàn thành';}
  for(const b of document.querySelectorAll('[data-word-key]')){const saved=!!store.data.words[b.dataset.wordKey];b.textContent=saved?'Đã lưu ✓':'Lưu từ';b.className=`small-button ${saved?'saved':'secondary'}`;b.setAttribute('aria-pressed',String(saved));}
 }
});
start();
