import {el,field,sourceLink,status,toast} from './dom.js';
const filterState={query:'',state:'all',group:'all'};
const attempts=new Map();
const fold=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
const gotoLesson=n=>location.hash=`lesson/${n}`;

export function roadmap(course,store,refresh){
 const next=store.next(),count=store.count();
 const start=el('button',{id:'continueLearning',onclick:()=>gotoLesson(next.number)},count===52?'Học lại từ đầu →':store.data.lastLesson?'Tiếp tục học →':'Bắt đầu bài 1 →');
 const hero=el('section',{class:'hero'},el('div',{},el('p',{class:'eyebrow'},'Lộ trình tự học · VOA Level 1'),el('h1',{},'Một bài nhỏ.\nMột bước tiến mới.'),el('p',{},course.description),el('div',{class:'metrics'},...[[52,'bài video'],[5,'chặng học'],['25′','gợi ý mỗi bài']].map(([a,b])=>el('div',{},el('strong',{},a),el('span',{},b))))),el('div',{class:'hero-card'},el('p',{class:'eyebrow'},count===52?'Bạn đã hoàn thành lộ trình':'Bài học dành cho hôm nay'),el('small',{},`Bài ${next.number} · ${next.topic}`),el('h2',{},next.title),el('p',{class:'muted'},next.objective),el('progress',{value:count,max:52,'aria-label':`${count} trên 52 bài hoàn thành`}),el('p',{class:'muted',id:'overallProgress'},`${count}/52 bài hoàn thành · ${Math.round(count/52*100)}%`),start));
 const query=el('input',{id:'lessonSearch',type:'search',placeholder:'Tên bài, chủ đề hoặc số bài…',value:filterState.query});
 const state=el('select',{id:'lessonFilter'},...[['all','Tất cả trạng thái'],['new','Chưa học'],['started','Đang học'],['complete','Hoàn thành']].map(([v,t])=>el('option',{value:v},t)));state.value=filterState.state;
 const group=el('select',{id:'groupFilter'},el('option',{value:'all'},'Tất cả chặng'),...course.groups.map((g,i)=>el('option',{value:String(i)},g.label)));group.value=filterState.group;
 const resultCount=el('p',{class:'muted',id:'searchResults',role:'status','aria-live':'polite'}),results=el('div',{id:'lessonResults'});
 function render(){results.replaceChildren();let total=0;course.groups.forEach((g,i)=>{if(filterState.group!=='all'&&+filterState.group!==i)return;const lessons=course.lessons.filter(l=>{const p=store.data.lessons[l.id];const s=p?.complete?'complete':p?.started?'started':'new';return l.number>=g.start&&l.number<=g.end&&(filterState.state==='all'||filterState.state===s)&&fold(`${l.number} ${l.title} ${l.topic} ${l.objective}`).includes(fold(filterState.query));});if(!lessons.length)return;total+=lessons.length;results.append(el('div',{class:'chapter-heading'},el('span',{class:'chapter-no'},`Chặng ${i+1}`),el('h2',{},g.label)),el('div',{class:'lesson-grid'},...lessons.map(l=>{const p=store.data.lessons[l.id];const s=p?.complete?'complete':p?.started?'started':'new';return el('article',{class:'lesson-card','data-lesson':l.number},el('div',{class:'card-top'},el('span',{},`Bài ${String(l.number).padStart(2,'0')} · ${l.minutes} phút`),el('span',{class:`badge ${s}`},s==='complete'?'Hoàn thành':s==='started'?'Đang học':'Chưa học')),el('h3',{},l.title),el('p',{},l.objective),el('a',{href:`#lesson/${l.number}`,'aria-label':`Mở bài ${l.number}: ${l.title}`},l.topic,el('span',{'aria-hidden':'true'},'↗')));})));});resultCount.textContent=`${total} bài phù hợp`;if(!total)results.append(el('div',{class:'empty'},el('h2',{},'Chưa tìm thấy bài phù hợp'),el('p',{},'Thử tên bài, chủ đề khác hoặc bỏ bộ lọc.'),el('button',{class:'secondary',onclick:()=>{filterState.query='';filterState.state='all';filterState.group='all';query.value='';state.value='all';group.value='all';render();query.focus();}},'Xóa bộ lọc')));}
 query.addEventListener('input',()=>{filterState.query=query.value;render();});state.addEventListener('change',()=>{filterState.state=state.value;render();});group.addEventListener('change',()=>{filterState.group=group.value;render();});render();
 return el('div',{},hero,el('div',{class:'section-top'},el('h2',{},'52 cuộc hội thoại, một lộ trình'),el('span',{class:'muted'},'Học theo thứ tự hoặc chọn chủ đề bạn cần')),el('div',{class:'filters'},field('Tìm bài học','lessonSearch',query),field('Trạng thái','lessonFilter',state),field('Chặng học','groupFilter',group)),resultCount,results);
}

function videoPanel(lesson){
 const stage=el('div',{class:'video-stage',id:'videoStage'}),note=el('p',{class:'status',role:'status',hidden:true});
 const select=el('select',{id:'videoChoice'},...lesson.media.map((m,i)=>el('option',{value:i},m.label)));
 const close=el('button',{class:'secondary',id:'closeVideo',hidden:true},'Đóng video');
 const load=el('button',{id:'loadVideo'},'Mở video VOA');
 function placeholder(){stage.classList.remove('has-video');stage.replaceChildren(el('span',{class:'video-symbol','aria-hidden':'true'},'▷'),el('h3',{},'Học từ cuộc hội thoại thật'),el('p',{},'Bấm “Mở video VOA” để kết nối với trình phát bên ngoài. Video không tự phát.'));close.hidden=true;status(note,'');}
 function open(){const media=lesson.media[+select.value];if(!media||!/^https:\/\/learningenglish\.voanews\.com\/embed\/player\/0\/\d+\.html\?type=video$/.test(media.embedUrl)){status(note,'Địa chỉ video không hợp lệ. Hãy mở bài gốc bên dưới.',true);return;}const frame=el('iframe',{id:'lessonVideo',src:media.embedUrl,title:`VOA bài ${lesson.number}: ${lesson.title} — ${media.label}`,allow:'fullscreen; picture-in-picture',allowfullscreen:true,sandbox:'allow-scripts allow-same-origin allow-popups allow-presentation',referrerpolicy:'strict-origin-when-cross-origin'});stage.classList.add('has-video');stage.replaceChildren(frame);close.hidden=false;status(note,'Đang tải trình phát. Nếu video không phát được, dùng liên kết bài gốc bên dưới.');frame.addEventListener('load',()=>status(note,'Trình phát đã mở. Bấm nút phát trong video để bắt đầu.'));frame.addEventListener('error',()=>status(note,'Không tải được trình phát. Bạn có thể mở bài gốc VOA.',true));}
 load.addEventListener('click',open);close.addEventListener('click',placeholder);select.addEventListener('change',placeholder);placeholder();
 return el('section',{class:'panel',id:'video'},el('h2',{},'01 · Xem & nghe'),el('p',{},lesson.instructions),el('div',{class:'video-toolbar'},field('Nội dung video','videoChoice',select),load,close),stage,note,el('p',{class:'video-note'},'Trình phát thuộc VOA và có thể kết nối các dịch vụ của nhà cung cấp. '),sourceLink(lesson.source.url,'Mở bài gốc VOA ↗'));
}

export function lessonView(course,store,number,refresh){
 const lesson=course.lessons[number-1];if(!lesson)return el('div',{class:'empty'},el('h1',{},'Không tìm thấy bài học'),el('a',{href:'#roadmap'},'Về lộ trình'));
 store.started(lesson.id);refresh();
 const attempt=attempts.get(lesson.id)||{answers:{},graded:false};attempts.set(lesson.id,attempt);
 const vocab=el('section',{class:'panel',id:'vocabulary'},el('h2',{},'02 · Từ & cụm từ'),el('p',{class:'muted'},'Lưu những từ bạn muốn ôn. Đọc ví dụ thành tiếng sau khi xem video.'),el('div',{class:'vocab-list'},...lesson.vocabulary.map((w,i)=>{const key=`${lesson.id}:${i}`;const button=el('button',{class:`small-button ${store.data.words[key]?'saved':'secondary'}`,'aria-label':`Lưu từ ${w.word}`,'aria-pressed':!!store.data.words[key],onclick:()=>{const saved=store.saveWord(lesson.id,i);button.textContent=saved?'Đã lưu ✓':'Lưu từ';button.className=`small-button ${saved?'saved':'secondary'}`;button.setAttribute('aria-pressed',String(saved));refresh();toast(saved?'Đã thêm từ vào Ôn tập.':'Đã bỏ từ khỏi Ôn tập.');}},store.data.words[key]?'Đã lưu ✓':'Lưu từ');return el('article',{class:'vocab-card'},el('div',{},el('h3',{lang:'en'},w.word),el('p',{},w.meaning),el('small',{lang:'en'},w.example)),button);})),el('h3',{},lesson.grammar.title),el('div',{class:'callout'},el('p',{},lesson.grammar.explanation),el('p',{lang:'en'},lesson.grammar.example)));
 const draft=el('textarea',{class:'practice-text',id:'practiceDraft',maxlength:3000,placeholder:'Viết câu của bạn ở đây… (chỉ giữ khi trang đang mở)'});
 const practice=el('section',{class:'panel',id:'practice'},el('h2',{},'03 · Dùng điều vừa học'),el('p',{},lesson.practice),field('Bản nháp luyện viết','practiceDraft',draft),el('p',{class:'video-note'},'Bản nháp không được lưu hoặc gửi đi. Đọc thành tiếng, rồi tự kiểm tra từ vựng và mẫu câu.'),el('div',{class:'callout'},el('strong',{},'Tự kiểm tra'),el('p',{},'Tôi đã dùng đúng ý nghĩa từ? Câu có chủ ngữ và động từ? Tôi có thể nói lại mà không nhìn ví dụ?')));
 const form=el('form',{id:'lessonQuiz',novalidate:true}),message=el('p',{class:'status',role:'status',hidden:true}),summary=el('div',{id:'quizSummary'}),explanations=[];
 lesson.quiz.forEach((q,i)=>{const exp=el('p',{class:'explanation',hidden:true});explanations.push(exp);form.append(el('fieldset',{class:'quiz-question'},el('legend',{},`${i+1}. ${q.prompt}`),...q.choices.map((c,j)=>el('label',{class:'quiz-option'},el('input',{type:'radio',name:q.id,value:j,checked:attempt.answers[q.id]===j,onchange:()=>{attempt.answers[q.id]=j;attempt.graded=false;}}),el('span',{lang:'en'},c))),exp));});
 const complete=el('button',{id:'completeLesson',type:'button',disabled:(store.data.lessons[lesson.id]?.best||0)<4,onclick:()=>{if(store.complete(lesson.id)){refresh();complete.textContent='Đã hoàn thành ✓';complete.disabled=true;toast(`Đã hoàn thành bài ${number}.`);}}},store.data.lessons[lesson.id]?.complete?'Đã hoàn thành ✓':'Đánh dấu hoàn thành');
 if(store.data.lessons[lesson.id]?.complete)complete.disabled=true;
 function feedback(score){explanations.forEach((n,i)=>{const q=lesson.quiz[i],ok=attempt.answers[q.id]===q.answer;n.hidden=false;n.classList.toggle('incorrect',!ok);n.textContent=`${ok?'Đúng':'Chưa đúng'} · ${q.explanation} Đáp án: ${q.choices[q.answer]}`;});summary.replaceChildren(el('div',{class:'quiz-summary',tabindex:-1,role:'status'},el('h3',{},`Lượt này: ${score}/5 câu đúng`),el('p',{},`Điểm tốt nhất: ${store.data.lessons[lesson.id]?.best||score}/5. ${score>=4?'Bạn có thể đánh dấu hoàn thành hoặc làm lại để củng cố.':'Đọc giải thích và thử lại. Cần ít nhất 4/5 để hoàn thành bài.'}`)));complete.disabled=store.data.lessons[lesson.id]?.complete===true||(store.data.lessons[lesson.id]?.best||0)<4;}
 form.addEventListener('submit',e=>{e.preventDefault();const missing=lesson.quiz.filter(q=>!Number.isInteger(attempt.answers[q.id]));if(missing.length){status(message,`Bạn còn ${missing.length} câu chưa trả lời. Hãy chọn đáp án cho đủ 5 câu.`,true);form.querySelector(`input[name="${missing[0].id}"]`).focus();return;}const score=lesson.quiz.filter(q=>attempt.answers[q.id]===q.answer).length;store.score(lesson.id,score);refresh();attempt.graded=true;attempt.score=score;status(message,'');feedback(score);summary.firstChild.focus();});
 const retry=el('button',{class:'secondary',type:'button',id:'retakeQuiz',onclick:()=>{attempt.answers={};attempt.graded=false;form.reset();for(const n of form.querySelectorAll('input'))n.checked=false;explanations.forEach(n=>n.hidden=true);summary.replaceChildren();status(message,'');form.querySelector('input').focus();}},'Làm lại');
 form.append(message,el('div',{class:'actions'},el('button',{type:'submit',id:'gradeQuiz'},'Kiểm tra đáp án'),retry),summary,el('div',{class:'actions'},complete));if(attempt.graded)feedback(attempt.score);
 const quiz=el('section',{class:'panel',id:'quiz'},el('h2',{},'04 · Kiểm tra điều đã học'),el('p',{class:'muted'},'5 câu tự luyện · cần 4 câu đúng để hoàn thành · có thể làm lại'),form);
 const side=el('aside',{class:'panel lesson-sidebar','aria-label':'Hướng dẫn học'},el('p',{class:'eyebrow'},`Bài ${number} / 52`),el('h2',{},'Học theo 4 bước'),el('ol',{},...['Xem để hiểu ý chính','Ghi nhớ từ và mẫu câu','Nói hoặc viết câu của bạn','Làm bài tập và ôn lại'].map(t=>el('li',{},t))),el('div',{class:'jump-links'},...[[ 'video','Xem video'],['vocabulary','Từ & mẫu câu'],['practice','Luyện tập'],['quiz','Bài tập']].map(([id,t])=>el('a',{href:`#lesson/${number}/${id}`},t))),el('p',{class:'source-credit'},'Video: VOA Learning English. Bài tập tự biên soạn.'),sourceLink(lesson.source.rightsUrl,'Thông tin quyền sử dụng ↗'));
 const bottom=el('div',{class:'lesson-bottom'},number>1?el('a',{href:`#lesson/${number-1}`},'← Bài trước'):el('span',{}),el('a',{href:'#roadmap'},'Về lộ trình'),number<52?el('a',{href:`#lesson/${number+1}`},'Bài tiếp →'):el('a',{href:'#review'},'Ôn lại từ đã lưu →'));
 return el('div',{},el('a',{class:'breadcrumb',href:'#roadmap'},'← Lộ trình tiếng Anh'),el('div',{class:'lesson-heading'},el('p',{class:'eyebrow'},`Bài ${number} · ${lesson.topic} · ${lesson.minutes} phút gợi ý`),el('h1',{lang:'en'},lesson.title),el('p',{class:'subheading'},lesson.objective)),el('div',{class:'lesson-layout'},el('div',{},videoPanel(lesson),vocab,practice,quiz,bottom),side));
}

export function reviewView(course,store,refresh){
 let index=0,revealed=false;const container=el('div',{}),body=el('div',{id:'flashcardArea'}),list=el('div',{class:'panel review-list'}),message=el('p',{class:'muted'});
 function words(){return Object.entries(store.data.words).map(([key,state])=>{const [id,i]=key.split(':');const lesson=course.lessons.find(l=>l.id===id);return {key,state,lesson,word:lesson?.vocabulary[+i]};}).filter(x=>x.word).sort((a,b)=>(a.state==='known'?1:0)-(b.state==='known'?1:0));}
 function draw(){const saved=words();refresh();message.textContent=`${saved.length} từ đã lưu · ${saved.filter(w=>w.state!=='known').length} từ cần ôn`;body.replaceChildren();list.replaceChildren();if(!saved.length){body.append(el('div',{class:'empty'},el('h2',{},'Bắt đầu từ một từ mới'),el('p',{},'Vào một bài học và bấm “Lưu từ”. Từ chưa nhớ sẽ được ưu tiên trong phần ôn tập.'),el('a',{href:`#lesson/${store.next().number}`},'Mở bài học →')));list.hidden=true;return;}list.hidden=false;index=Math.min(index,saved.length-1);const x=saved[index];const answer=el('div',{hidden:!revealed,id:'flashcardAnswer'},el('p',{class:'meaning'},x.word.meaning),el('p',{lang:'en'},x.word.example));const flip=el('button',{class:'secondary',id:'flipCard',onclick:()=>{revealed=!revealed;answer.hidden=!revealed;flip.textContent=revealed?'Ẩn nghĩa':'Xem nghĩa & ví dụ';known.disabled=!revealed;unknown.disabled=!revealed;}},revealed?'Ẩn nghĩa':'Xem nghĩa & ví dụ');
 const next=()=>{index=(index+1)%saved.length;revealed=false;draw();};
 const known=el('button',{id:'knowWord',disabled:!revealed,onclick:()=>{store.wordState(x.key,'known');next();toast('Đã đánh dấu nhớ.');}},'Đã nhớ');const unknown=el('button',{class:'secondary',id:'unknownWord',disabled:!revealed,onclick:()=>{store.wordState(x.key,'unknown');next();toast('Từ này sẽ được ưu tiên ôn lại.');}},'Chưa nhớ');
 body.append(el('section',{class:'panel flashcard','aria-label':'Thẻ ôn từ vựng'},el('p',{class:'eyebrow'},`Thẻ ${index+1}/${saved.length} · Bài ${x.lesson.number}`),el('h2',{lang:'en'},x.word.word),flip,answer,el('div',{class:'actions'},unknown,known,el('button',{class:'secondary',id:'nextCard',onclick:next},'Thẻ tiếp →'))));
 list.append(el('h2',{},'Sổ từ của bạn'),...saved.map(x=>el('div',{class:'review-word'},el('div',{},el('strong',{lang:'en'},x.word.word),el('p',{class:'muted'},x.word.meaning),el('small',{},`Bài ${x.lesson.number} · ${x.state==='known'?'Đã nhớ':'Cần ôn'}`)),el('div',{class:'actions'},el('a',{href:`#lesson/${x.lesson.number}/vocabulary`},'Về bài học'),el('button',{class:'text-button','aria-label':`Bỏ từ ${x.word.word}`,onclick:()=>{store.removeWord(x.key);revealed=false;draw();toast('Đã bỏ từ đã lưu.');}},'Bỏ từ')))));
 }
 container.append(el('p',{class:'eyebrow'},'Ôn tập'),el('h1',{},'Nhớ lâu hơn, từng từ một.'),el('p',{class:'subheading'},'Thử nhớ nghĩa trước khi lật thẻ. Đánh dấu “Chưa nhớ” để ưu tiên luyện lại.'),message,body,list);draw();return container;
}
