import {el,field,status,toast} from './dom.js';
const LANGUAGES=[['vi','Tiếng Việt'],['en','Tiếng Anh'],['fr','Tiếng Pháp'],['es','Tiếng Tây Ban Nha'],['ja','Tiếng Nhật'],['ko','Tiếng Hàn'],['zh','Tiếng Trung']];
const VOICES={vi:'vi-VN',en:'en-US',fr:'fr-FR',es:'es-ES',ja:'ja-JP',ko:'ko-KR',zh:'zh-CN'};
const HISTORY='neural-lingua.translation-history.v1',PREF='neural-lingua.translation-preference.v1';
export function translatorView(){
 let alive=true,request=null,version=0,detected='vi',valid=false,recognition=null,listening=false,history=[],saveHistory=false;
 const source=el('select',{id:'sourceLanguage'},el('option',{value:'auto'},'Tự phát hiện'),...LANGUAGES.map(([v,t])=>el('option',{value:v},t))),target=el('select',{id:'targetLanguage'},...LANGUAGES.map(([v,t])=>el('option',{value:v},t)));target.value='en';
 const input=el('textarea',{id:'textInput',maxlength:5000,placeholder:'Nhập văn bản cần dịch…',spellcheck:true}),output=el('textarea',{id:'translatedText',readonly:true,placeholder:'Bản dịch sẽ xuất hiện ở đây…'}),counter=el('div',{class:'char-count',id:'charCount'},'0 / 5000');
 const message=el('p',{class:'status',id:'translationStatus',role:'status','aria-live':'polite',hidden:true});
 const translate=el('button',{id:'translateButton'},'Dịch văn bản'),cancel=el('button',{class:'secondary',id:'cancelTranslation',hidden:true},'Hủy'),retry=el('button',{class:'secondary',id:'retryTranslation',hidden:true},'Thử lại');
 const copy=el('button',{class:'secondary',id:'copyTranslation',disabled:true},'Sao chép'),play=el('button',{id:'playButton',disabled:true},'Nghe bản dịch'),stop=el('button',{class:'secondary',id:'stopSpeech',disabled:true},'Dừng nghe'),record=el('button',{class:'secondary',id:'recordButton'},'Ghi âm'),clear=el('button',{class:'secondary',id:'clearTranslation'},'Xóa');
 const historyBox=el('section',{class:'panel',id:'translationHistory'}),historyList=el('div',{}),toggle=el('input',{type:'checkbox',id:'saveTranslationHistory'}),historyMessage=el('p',{class:'status',role:'status',hidden:true});
 const allowed=new Set(LANGUAGES.map(x=>x[0]));
 function readHistory(){try{saveHistory=JSON.parse(localStorage.getItem(PREF)||'false')===true;const raw=saveHistory?JSON.parse(localStorage.getItem(HISTORY)||'[]'):[];if(!Array.isArray(raw))throw new Error('Invalid history');history=raw.filter(x=>x&&typeof x.input==='string'&&typeof x.output==='string'&&x.input.length<=5000&&x.output.length<=20000&&(x.from==='auto'||allowed.has(x.from))&&allowed.has(x.to)&&Number.isFinite(x.time)).slice(0,20);}catch{history=[];status(historyMessage,'Không đọc được lịch sử. Bạn vẫn có thể dịch; dữ liệu hỏng không được dùng.',true);}}
 function storeHistory(){if(!saveHistory)return;try{localStorage.setItem(HISTORY,JSON.stringify(history));}catch{status(historyMessage,'Không thể lưu lịch sử trên thiết bị. Bản dịch chỉ giữ trong phiên này.',true);}}
 function resultState(value){valid=value;copy.disabled=!value;play.disabled=!value||!('speechSynthesis' in window&&'SpeechSynthesisUtterance' in window);}
 function stopAudio(){if('speechSynthesis'in window)window.speechSynthesis.cancel();stop.disabled=true;}
 function stopRecording(){if(recognition){try{recognition.abort();}catch{}recognition=null;}listening=false;record.textContent='Ghi âm';record.setAttribute('aria-pressed','false');}
 function abort(messageText=''){version++;if(request)request.abort();request=null;translate.disabled=false;cancel.hidden=true;if(messageText)status(message,messageText);}
 function changed(){abort();stopAudio();resultState(false);counter.textContent=`${input.value.length} / 5000`;retry.hidden=true;if(output.value)status(message,'Nội dung hoặc ngôn ngữ đã thay đổi. Bấm Dịch để cập nhật kết quả.');else status(message,'');}
 async function run(){
  const text=input.value.trim();if(!text||text.length>5000){abort();resultState(false);status(message,'Nhập từ 1 đến 5.000 ký tự để dịch.',true);input.focus();return;}
  abort();stopAudio();resultState(false);retry.hidden=true;
  const seq=version,from=source.value,to=target.value,controller=new AbortController();request=controller;let timedOut=false;
  translate.disabled=true;cancel.hidden=false;status(message,'Đang dịch… Bạn có thể hủy hoặc thay đổi nội dung.');
  const timeout=setTimeout(()=>{timedOut=true;controller.abort();},15000);
  try{
   let translation,language=from;
   if(from===to){translation=text;}else{
    const params=new URLSearchParams({client:'gtx',sl:from,tl:to,dt:'t',q:text});
    const response=await fetch(`https://translate.googleapis.com/translate_a/single?${params}`,{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});
    if(!response.ok)throw new Error('Service unavailable');
    const data=await response.json();if(!Array.isArray(data)||!Array.isArray(data[0]))throw new Error('Invalid response');
    translation=data[0].filter(Array.isArray).map(x=>typeof x[0]==='string'?x[0]:'').join('');if(!translation||translation.length>20000)throw new Error('Invalid translation');
    language=allowed.has(data[2])?data[2]:'vi';
   }
   if(!alive||seq!==version)return;detected=language;output.value=translation;resultState(true);status(message,from==='auto'?`Đã dịch · ngôn ngữ phát hiện: ${LANGUAGES.find(x=>x[0]===detected)?.[1]||detected}`:'Đã dịch.');
   if(saveHistory){history.unshift({input:text,output:translation,from,to,time:Date.now()});history=history.slice(0,20);storeHistory();drawHistory();}
  }catch(error){if(!alive||seq!==version)return;resultState(false);status(message,timedOut?'Dịch vụ phản hồi quá lâu (15 giây). Hãy thử lại.':'Không thể dịch lúc này. Kiểm tra mạng hoặc thử lại sau.',true);retry.hidden=false;}
  finally{clearTimeout(timeout);if(alive&&seq===version){request=null;translate.disabled=false;cancel.hidden=true;}}
 }
 function drawHistory(){toggle.checked=saveHistory;historyList.replaceChildren();if(!saveHistory){historyList.append(el('p',{class:'muted'},'Lịch sử đang tắt. Văn bản sẽ không được lưu vào lịch sử trên thiết bị.'));return;}if(!history.length){historyList.append(el('p',{class:'muted'},'Chưa có bản dịch đã lưu.'));return;}historyList.append(...history.map((x,i)=>el('article',{class:'history-entry'},el('small',{},`${new Date(x.time).toLocaleString('vi-VN')} · ${x.from} → ${x.to}`),el('p',{},x.input),el('p',{},x.output),el('div',{class:'actions'},el('button',{class:'secondary small-button',onclick:()=>{abort();stopAudio();input.value=x.input;output.value=x.output;source.value=x.from;target.value=x.to;counter.textContent=`${input.value.length} / 5000`;resultState(true);status(message,'Đã khôi phục bản dịch từ lịch sử.');input.focus();}},'Dùng lại'),el('button',{class:'text-button','aria-label':`Xóa bản dịch ${i+1}`,onclick:()=>{history.splice(i,1);storeHistory();drawHistory();toast('Đã xóa mục lịch sử.');}},'Xóa mục')))));}
 readHistory();drawHistory();
 toggle.addEventListener('change',()=>{saveHistory=toggle.checked;try{localStorage.setItem(PREF,JSON.stringify(saveHistory));if(!saveHistory){localStorage.removeItem(HISTORY);history=[];}else storeHistory();status(historyMessage,'');}catch{status(historyMessage,'Không thể thay đổi dữ liệu lưu. Hãy kiểm tra quyền lưu trữ của trình duyệt.',true);}drawHistory();});
 historyBox.append(el('div',{class:'history-title'},el('h2',{},'Lịch sử trên thiết bị'),el('label',{},toggle,' Lưu lịch sử dịch')),el('p',{class:'video-note'},'Mặc định tắt · tối đa 20 mục · tắt lưu sẽ xóa lịch sử đã lưu.'),el('button',{class:'text-button',id:'clearTranslationHistory',onclick:()=>{history=[];try{localStorage.removeItem(HISTORY);status(historyMessage,'Đã xóa toàn bộ lịch sử.');}catch{status(historyMessage,'Không thể xóa dữ liệu lưu. Hãy dùng quản lý dữ liệu trang của trình duyệt.',true);}drawHistory();}},'Xóa toàn bộ lịch sử'),historyMessage,historyList);
 translate.addEventListener('click',run);retry.addEventListener('click',run);cancel.addEventListener('click',()=>abort('Đã hủy yêu cầu dịch.'));input.addEventListener('input',changed);source.addEventListener('change',changed);target.addEventListener('change',changed);
 input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();if(!request)run();}});
 copy.addEventListener('click',async()=>{if(!valid)return;try{if(!navigator.clipboard?.writeText)throw new Error('Unsupported clipboard');await navigator.clipboard.writeText(output.value);if(alive)toast('Đã sao chép bản dịch.');}catch{if(alive){output.focus();output.select();status(message,'Trình duyệt chưa cho phép sao chép. Bản dịch đã được chọn; nhấn Ctrl+C hoặc Cmd+C.');}}});
 play.addEventListener('click',()=>{if(!valid||!('speechSynthesis'in window)||!('SpeechSynthesisUtterance'in window))return;stopAudio();const speech=new SpeechSynthesisUtterance(output.value);speech.lang=VOICES[target.value];speech.onend=()=>{if(alive)stop.disabled=true;};speech.onerror=()=>{if(alive){stop.disabled=true;status(message,'Không phát được giọng đọc. Kiểm tra giọng nói của trình duyệt.',true);}};window.speechSynthesis.speak(speech);stop.disabled=false;});stop.addEventListener('click',stopAudio);
 const speechAPI=window.SpeechRecognition||window.webkitSpeechRecognition;
 record.setAttribute('aria-pressed','false');if(!speechAPI){record.disabled=true;record.title='Trình duyệt này không hỗ trợ nhận diện giọng nói.';}
 record.addEventListener('click',()=>{if(listening){stopRecording();status(message,'Đã dừng ghi âm.');return;}if(!speechAPI)return;stopAudio();abort();recognition=new speechAPI();recognition.lang=VOICES[source.value==='auto'?detected:source.value];recognition.interimResults=false;recognition.maxAlternatives=1;
  recognition.onresult=e=>{if(!alive)return;input.value=Array.from(e.results).map(r=>r[0]?.transcript||'').join(' ').slice(0,5000);changed();status(message,'Đã nhập lời nói. Kiểm tra nội dung rồi bấm Dịch.');};
  recognition.onerror=e=>{if(!alive)return;const errors={'not-allowed':'Bạn chưa cho phép dùng micro. Có thể tiếp tục bằng cách nhập văn bản.','audio-capture':'Không tìm thấy micro. Hãy nhập văn bản hoặc kiểm tra thiết bị.','no-speech':'Chưa nghe thấy lời nói. Bạn có thể thử ghi âm lại.','network':'Dịch vụ nhận diện giọng nói chưa kết nối được.'};status(message,errors[e.error]||'Không nhận diện được giọng nói. Bạn có thể nhập văn bản.',true);};
  recognition.onend=()=>{listening=false;recognition=null;if(alive){record.textContent='Ghi âm';record.setAttribute('aria-pressed','false');}};
  try{recognition.start();listening=true;record.textContent='Dừng ghi âm';record.setAttribute('aria-pressed','true');status(message,'Đang nghe… Nhận diện giọng nói có thể dùng dịch vụ của trình duyệt.');}catch{stopRecording();status(message,'Không khởi động được micro. Bạn có thể nhập văn bản.',true);}
 });
 clear.addEventListener('click',()=>{abort();stopAudio();stopRecording();input.value='';output.value='';resultState(false);counter.textContent='0 / 5000';status(message,'');retry.hidden=true;input.focus();});
 const swap=el('button',{class:'secondary',id:'swapButton','aria-label':'Đảo ngôn ngữ và văn bản',onclick:()=>{abort();stopAudio();stopRecording();const from=source.value,to=target.value,old=input.value;source.value=to;target.value=from==='auto'?detected:from;input.value=valid?output.value.slice(0,5000):old;output.value=valid?old:'';resultState(false);counter.textContent=`${input.value.length} / 5000`;status(message,'Đã đảo chiều. Bấm Dịch để cập nhật kết quả.');}},'⇄');
 const container=el('div',{},el('p',{class:'eyebrow'},'Công cụ hỗ trợ'),el('h1',{},'Hiểu thêm một câu mới.'),el('p',{class:'subheading'},'Văn bản được gửi tới dịch vụ Google bên ngoài khi bấm Dịch. Tránh nhập thông tin riêng tư. Dịch vụ thử nghiệm có thể gián đoạn.'),el('div',{class:'translator-grid'},el('section',{class:'panel translator-panel'},field('Ngôn ngữ nguồn','sourceLanguage',source),field('Văn bản cần dịch','textInput',input),counter,el('div',{class:'actions translator-actions'},translate,record,clear,cancel,retry)),el('div',{class:'swap-wrap'},swap),el('section',{class:'panel translator-panel'},field('Ngôn ngữ đích','targetLanguage',target),field('Bản dịch','translatedText',output),el('div',{class:'actions translator-actions'},copy,play,stop))),message,!speechAPI?el('p',{class:'video-note'},'Trình duyệt này chưa hỗ trợ ghi âm. Nhập văn bản để tiếp tục; giọng đọc tùy giọng có sẵn trên thiết bị.'):el('p',{class:'video-note'},'Micro chỉ bật khi bạn bấm Ghi âm. Nhận diện giọng nói có thể xử lý qua dịch vụ của trình duyệt.'),historyBox);
 return {node:container,destroy(){alive=false;abort();stopAudio();stopRecording();}};
}
