const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const base=process.env.PREVIEW_URL||'http://127.0.0.1:8831',out=process.env.QA_OUT_DIR||path.resolve(__dirname,'../test-results');
const course=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../data/course.json'),'utf8'));const results=[];
const ready=async(p,r='lesson/1')=>{await p.goto(base+'/#'+r);await p.locator('main[aria-busy=false]').waitFor();};
const save=async(p,w)=>{const b=p.getByRole('button',{name:`Lưu từ ${w}`,exact:true});await b.click();await p.waitForFunction(word=>document.querySelector(`button[aria-label="Lưu từ ${word}"]`)?.getAttribute('aria-pressed')==='true',w);};
const grade=async(p,n=5)=>{for(const [i,q] of course.lessons[0].quiz.entries())await p.locator(`input[name="${q.id}"][value="${i<n?q.answer:(q.answer+1)%4}"]`).check();await p.locator('#gradeQuiz').click();await p.locator('#quizSummary .quiz-summary').waitFor();};
async function test(name,fn){await fn();results.push({name,passed:true});console.log('PASS',name);}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const ctx=await browser.newContext(),a=await ctx.newPage(),b=await ctx.newPage();await Promise.all([ready(a),ready(b)]);
await test('Concurrent saves from two tabs preserve both words',async()=>{assert(await a.evaluate(()=>!!navigator.locks?.request));await Promise.all([save(a,'hello'),save(b,'welcome')]);for(const p of [a,b])await p.waitForFunction(()=>document.querySelector('#savedCount').textContent==='2');});
await test('Stale tab writes preserve highest score and completion',async()=>{await grade(a);await a.locator('#completeLesson').click();await a.waitForFunction(()=>document.querySelector('#completeLesson').textContent.includes('Đã hoàn thành'));await save(b,'apartment');const c=await ctx.newPage();await ready(c);assert.match(await c.locator('#savedLessonScore').innerText(),/5\/5 · Đã hoàn thành/);assert.equal(await c.locator('#savedCount').innerText(),'3');await c.close();});
await test('Concurrent scores do not lower best score',async()=>{await Promise.all([grade(a,5),grade(b,1)]);await b.reload();await b.locator('#savedLessonScore').waitFor();assert.match(await b.locator('#savedLessonScore').innerText(),/5\/5 · Đã hoàn thành/);});
await test('Disabling in one tab prevents stale tab persistence',async()=>{await a.locator('#saveProgress').uncheck();await a.waitForFunction(()=>!document.querySelector('#saveProgress').disabled);await b.waitForFunction(()=>!document.querySelector('#saveProgress').checked);await save(b,'nice to meet you');assert.equal(await b.evaluate(()=>localStorage.getItem('neural-lingua.learning.v1')),null);const c=await ctx.newPage();await ready(c,'review');assert.equal(await c.locator('#savedCount').innerText(),'0');await c.close();});
await test('Reset propagates even when storage was disabled and cannot resurrect old state',async()=>{await a.locator('#resetProgress').click();await a.locator('#confirmReset').click();await a.locator('#lessonSearch').waitFor();await b.waitForFunction(()=>document.querySelector('#savedCount').textContent==='0');await b.locator('#saveProgress').check();await b.waitForFunction(()=>!document.querySelector('#saveProgress').disabled);await ready(b);await save(b,'name');const data=await b.evaluate(()=>JSON.parse(localStorage.getItem('neural-lingua.learning.v1')));assert.deepEqual(Object.keys(data.words),['voa-en-1-01:2']);assert.equal(data.lessons['voa-en-1-01'].best,0);assert.equal(data.lessons['voa-en-1-01'].complete,false);});
await test('Keyboard focus follows flashcards; pending/all scopes and empty state work',async()=>{const solo=await browser.newContext(),p=await solo.newPage();await ready(p);await save(p,'hello');await save(p,'welcome');await ready(p,'review');await p.locator('#flipCard').click();await p.locator('#knowWord').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.activeElement?.id==='flipCard');assert.equal(await p.locator('.flashcard h2').innerText(),'welcome');await p.keyboard.press('Enter');assert(!(await p.locator('#knowWord').isDisabled()));await p.locator('#knowWord').click();await p.locator('#reviewAll').waitFor();assert.match(await p.locator('#flashcardArea').innerText(),/Bạn đã nhớ mọi từ/);await p.locator('#reviewScope').selectOption('all');assert.equal(await p.locator('#flipCard').count(),1);assert.match(await p.locator('.flashcard .eyebrow').innerText(),/1\/2/);await solo.close();});
await test('Document titles match route and writing52 has past/future',async()=>{await ready(a,'lesson/52');assert.match(await a.title(),/Bài 52: Taking Chances/);await a.locator('#writingModel summary').click();const model=await a.locator('#writingModel p').first().innerText();assert.match(model,/failed/);assert.match(model,/going to/);await ready(a,'sources');assert.match(await a.title(),/Nguồn & quyền riêng tư/);await ready(a,'translate');assert.match(await a.title(),/Dịch văn bản/);});
await test('Translation history opt-out in one tab prevents other tab restoring it',async()=>{await ctx.route('https://translate.googleapis.com/**',r=>{const text=new URL(r.request().url()).searchParams.get('q');return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify([[[text,'']],null,'vi'])});});await Promise.all([ready(a,'translate'),ready(b,'translate')]);await a.locator('#saveTranslationHistory').check();await a.waitForFunction(()=>!document.querySelector('#saveTranslationHistory').disabled);await b.waitForFunction(()=>document.querySelector('#saveTranslationHistory').checked);await Promise.all([a.locator('#textInput').fill('History A'),b.locator('#textInput').fill('History B')]);await Promise.all([a.locator('#translateButton').click(),b.locator('#translateButton').click()]);await a.waitForFunction(()=>document.querySelectorAll('.history-entry').length===2);await a.locator('#saveTranslationHistory').uncheck();await a.waitForFunction(()=>!document.querySelector('#saveTranslationHistory').disabled);await b.waitForFunction(()=>!document.querySelector('#saveTranslationHistory').checked);await b.locator('#textInput').fill('After opt-out');await b.locator('#translateButton').click();await b.waitForFunction(()=>document.querySelector('#translatedText').value==='After opt-out'&&!document.querySelector('#translateButton').disabled);assert.equal(await b.evaluate(()=>localStorage.getItem('neural-lingua.translation-history.v1')),null);});
await ctx.close();fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'multi-tab-results.json'),JSON.stringify({passed:results.length,tests:results},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1);});
