// Lifecycle/error fixtures exercise real MediaRecorder + Web Audio in Edge.
// Model accuracy is covered separately by real-model browser checks, not these fixtures.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.PREVIEW_URL||'http://127.0.0.1:8831';
const out=process.env.QA_OUT_DIR||path.resolve(__dirname,'../test-results');
fs.mkdirSync(out,{recursive:true});const results=[];let browser;
const mockWorker=mode=>`self.addEventListener('message',({data:d})=>{
 if(d.type==='prepare')setTimeout(()=>postMessage({id:d.id,type:${JSON.stringify(mode==='load-error'?'error':'ready')},phase:'prepare'}),${mode==='slow-load'?700:20});
 if(d.type==='transcribe')setTimeout(()=>postMessage({id:d.id,type:${JSON.stringify(mode==='empty'?'empty':mode==='asr-error'?'error':'result')},phase:'transcribe',text:'Recognized speech ('+d.language+').'}),700);
});`;
async function page(mode='normal',init){
 const ctx=await browser.newContext({permissions:['microphone']});
 await ctx.addInitScript(()=>{
  window.voiceStreams=[];window.voiceAccesses=0;
  const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
  navigator.mediaDevices.getUserMedia=async function(options){window.voiceAccesses++;const s=await original(options);window.voiceStreams.push(s);return s;};
  for(const key of ['SpeechRecognition','webkitSpeechRecognition'])Object.defineProperty(window,key,{configurable:true,get(){throw new Error('Browser recognition must not be used');}});
 });
 if(init)await ctx.addInitScript(init);
 const p=await ctx.newPage();let workers=0;
 await p.route('**/js/voice-worker.js',r=>{workers++;return r.fulfill({contentType:'text/javascript',body:mockWorker(mode)});});
 await p.goto(base+'/#translate');await p.locator('main[aria-busy=false]').waitFor();
 return {ctx,p,workers:()=>workers};
}
const prepare=async p=>{await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#recordButton').textContent==='Ghi âm');};
const record=async p=>{await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#recordButton').getAttribute('aria-pressed')==='true');await p.waitForTimeout(400);};
const transcribe=async p=>{await record(p);await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.startsWith('Đang nhận diện'));};
const tracksEnded=p=>p.evaluate(()=>window.voiceStreams.every(s=>s.getTracks().every(t=>t.readyState==='ended')));
async function test(name,fn){await fn();results.push(name);console.log('PASS',name);}
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 await test('No worker/model/microphone before explicit preparation; no Web Speech dependency',async()=>{const {ctx,p,workers}=await page();assert.equal(workers(),0);assert.equal(await p.evaluate(()=>voiceAccesses),0);assert(await p.locator('#recordButton').isEnabled());await prepare(p);assert.equal(workers(),1);assert.equal(await p.evaluate(()=>voiceAccesses),0);await ctx.close();});
 await test('Cancel model preparation ignores late ready',async()=>{const {ctx,p}=await page('slow-load');await p.locator('#recordButton').click();await p.locator('#cancelVoice').click();await p.waitForTimeout(800);assert.equal(await p.locator('#recordButton').innerText(),'Chuẩn bị ghi âm');assert.equal(await p.evaluate(()=>voiceAccesses),0);await ctx.close();});
 await test('Model load error gives retry and input still works',async()=>{const {ctx,p}=await page('load-error');await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.includes('Không tải'));assert(await p.locator('#recordButton').isEnabled());await p.locator('#textInput').fill('Continue typing');await ctx.close();});
 await test('Denied permission gives specific micro guidance',async()=>{const {ctx,p}=await page('normal',()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await prepare(p);await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.includes('chưa cho phép'));assert(await p.locator('#recordButton').isEnabled());await ctx.close();});
 await test('Cancel while permission pending stops stream acquired later',async()=>{const {ctx,p}=await page('normal',()=>{const original=navigator.mediaDevices.getUserMedia;navigator.mediaDevices.getUserMedia=async o=>{const s=await original(o);await new Promise(r=>setTimeout(r,600));return s;};});await prepare(p);await p.locator('#recordButton').click();await p.waitForFunction(()=>window.voiceStreams.length>0);await p.locator('#cancelVoice').click();await p.waitForTimeout(750);assert(await tracksEnded(p));assert.equal(await p.locator('#recordButton').getAttribute('aria-pressed'),'false');await ctx.close();});
 await test('Real capture/decoding stops tracks; selected language reaches worker; append preserves text',async()=>{const {ctx,p}=await page();await p.locator('#sourceLanguage').selectOption('vi');await prepare(p);await p.locator('#textInput').fill('Earlier text.');await transcribe(p);assert(await tracksEnded(p));await p.waitForFunction(()=>document.querySelector('#textInput').value.includes('Recognized'));assert.equal(await p.locator('#textInput').inputValue(),'Earlier text. Recognized speech (vi).');await ctx.close();});
 for(const action of ['cancel','edit','language','clear','route'])await test(`Pending transcription discarded after ${action}`,async()=>{const {ctx,p}=await page();await prepare(p);await transcribe(p);if(action==='cancel')await p.locator('#cancelVoice').click();if(action==='edit')await p.locator('#textInput').fill('New draft');if(action==='language')await p.locator('#sourceLanguage').selectOption('ja');if(action==='clear')await p.locator('#clearTranslation').click();if(action==='route')await p.locator('[data-nav=roadmap]').click();await p.waitForTimeout(850);assert(await tracksEnded(p));if(action!=='route')assert.equal(await p.locator('#textInput').inputValue(),action==='edit'?'New draft':'');else assert.equal(await p.locator('#recordButton').count(),0);await ctx.close();});
 await test('Leaving page during active recording turns off all tracks',async()=>{const {ctx,p}=await page();await prepare(p);await record(p);await p.locator('[data-nav=roadmap]').click();await p.waitForTimeout(100);assert(await tracksEnded(p));await ctx.close();});
 await test('No speech and inference error preserve draft with actionable notice',async()=>{for(const mode of ['empty','asr-error']){const {ctx,p}=await page(mode);await prepare(p);await p.locator('#textInput').fill('Keep this');await transcribe(p);await p.waitForFunction(()=>!document.querySelector('#recordButton').disabled);assert.equal(await p.locator('#textInput').inputValue(),'Keep this');assert.match(await p.locator('#voiceStatus').innerText(),mode==='empty'?/Chưa nghe rõ/:/Không nhận diện/);assert(await tracksEnded(p));await ctx.close();}});
 await test('5000-character limit prevents capture; append truncation is disclosed',async()=>{const {ctx,p}=await page();await prepare(p);await p.locator('#textInput').fill('x'.repeat(5000));await p.locator('#recordButton').click();assert.equal(await p.evaluate(()=>voiceAccesses),0);assert.match(await p.locator('#translationStatus').innerText(),/đủ 5.000/);await p.locator('#textInput').fill('x'.repeat(4998));await transcribe(p);await p.waitForFunction(()=>!document.querySelector('#recordButton').disabled);assert.equal((await p.locator('#textInput').inputValue()).length,5000);assert.match(await p.locator('#voiceStatus').innerText(),/vượt giới hạn/);await ctx.close();});
 await test('Model-cache deletion preserves unrelated cache and learning state',async()=>{const {ctx,p}=await page();await p.evaluate(async()=>{const c=await caches.open('voice-test');await c.put('/voice-assets/models/Xenova/whisper-tiny/config.json',new Response('model'));await c.put('/unrelated',new Response('keep'));localStorage.setItem('voice-sentinel','keep');});await p.locator('#clearVoiceModel').click();await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.includes('Đã xóa model'));assert.deepEqual(await p.evaluate(async()=>{const c=await caches.open('voice-test');return [!!await c.match('/voice-assets/models/Xenova/whisper-tiny/config.json'),!!await c.match('/unrelated'),localStorage.getItem('voice-sentinel')];}),[false,true,'keep']);await ctx.close();});
 await test('Inference deadline terminates work and discards late transcript',async()=>{const {ctx,p}=await page('normal',()=>{const original=setTimeout;window.setTimeout=(f,n,...a)=>original(f,n===120000?40:n,...a);});await prepare(p);await transcribe(p);await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.includes('quá lâu'));await p.waitForTimeout(850);assert.equal(await p.locator('#textInput').inputValue(),'');assert(await tracksEnded(p));assert(await p.locator('#recordButton').isEnabled());await ctx.close();});
 await test('Recorder initialization failure releases acquired microphone',async()=>{const {ctx,p}=await page('normal',()=>{window.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){throw new Error('Unsupported recorder');}};});await prepare(p);await p.locator('#recordButton').click();await p.waitForFunction(()=>document.querySelector('#voiceStatus').textContent.includes('Không mở được'));assert(await tracksEnded(p));await ctx.close();});
 await browser.close();fs.writeFileSync(path.join(out,'voice-results.json'),JSON.stringify({passed:results.length,results,limits:'Worker transcription/model output mocked; capture/MediaRecorder/decoding is real browser fake-device audio. Real Whisper checks recorded separately.'},null,2));
})().catch(async e=>{console.error(e.stack);fs.writeFileSync(path.join(out,'voice-results.json'),JSON.stringify({passed:results.length,results,error:e.message},null,2));await browser?.close();process.exit(1);});
